### ISSUE TITLE
Unable to do npm i

### ISSUE THREAD

**Issue by eugeneo** [microsoft/vscode-node-debug#194]
I did the following:

1. Cloned this repo.
2. Went to the new folder.
3. Ran `npm i`

Operation failed with an obscure error:

 node-debug@0.1.0 prepublish /Users/eostroukhov/git/vscode/vscode-node-debug
 gulp build

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/eostroukhov/git/vscode/vscode-node-debug/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/eostroukhov/git/vscode/vscode-node-debug/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/eostroukhov/git/vscode/vscode-node-debug/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nrdp-debug@0.1.0 prepublish: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nrdp-debug@0.1.0 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eostroukhov/.npm/_logs/2019-07-09T23_01_16_799Z-debug.log

**Comment by eugeneo** [comment]
Node.js 12 cannot be used.
