### ISSUE TITLE
Heating and high fan speeds when debugging node.js apps in Mac

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#25]
_From @karsep5 on November 26, 2015 5:29_

When stepping through code while debugging node application, in addition to unresponsiveness every now and then, my Macbook gets really hot with the CPU fan going supersonic. Seems to occur only when trying to step through the code. Running the program when it is just attached does not seem to have problems.

_Copied from original issue: Microsoft/vscode#688_

**Comment by ChuckJonas** [comment]
@weinand I just started having this issue...  When I try to inspect certain elements, VS-code becomes unresponsive and my CPU shoots up to 100% & memory jump to over a 1 gb. 

Then I'll get an error:
```
messageService.ts:128 Request 'continue' was cancelled because Node.js is unresponsive.: Error: Request 'continue' was cancelled because Node.js is unresponsive.
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:88:22168
    at Object.v [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:8549)
    at Object.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12054)
    at _run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:13375)
    at _error (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12892)
    at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:9407
    at t.e.dispatch (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:10752)
    at t.e.handleData (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:10264)
    at Socket.<anonymous> (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:83:9267)
    at emitOne (events.js:96:13)```

and eventually things will calm back down.  I can never actually get the inspected variable to show.  After VS-Code starts to respond again I just see `<...>` for the value of the variable I tried to inspect.  

The program itself runs fine on its own, so I don't think it's a memory leak on my end (could be wrong but I also have reverted back to code that I know I was able to debug and it's still happening)

**Comment by weinand** [comment]
@ChuckJonas are you inspecting large data structures?

**Comment by ChuckJonas** [comment]
Yes, it was about 2mb in size.  I switched to the experimental debugger and everything is good now.

**Comment by weinand** [comment]
@ChuckJonas yes, the old v8 debug protocol cannot deal with large data structures.
